version: 2
models:
  - name: client_by_account_status
    description: "Aggregate clients by status"
    meta:
      owner: "reporting team"
    config:
      schema: "transformed"
      materialized: "view"
    columns:
      - name: "account_status"
        description: "Account status ACTIVE/INACTIVE"
        tests:
         - accepted_values:
              values: ['active', 'inactive']
      - name: "clients_by_status"
        description: "Number of clients by account status" 
  
  - name: value_volume
    description: "Aggregate number and amount of payments by month per payee id"
    meta:
      owner: "reporting team"
    config:
      schema: "transformed"
      materialized: "view"
    tests:
      - not_empty